from github import Github
from urllib.parse import urlparse
import os
import time

def create_pull_request(repo_url, fix_code, file_path, reasoning_steps=None):
    """
    Creates a pull request with AI-generated code.
    - fix_code: Only the Python/fix code (no English reasoning)
    - reasoning_steps: Optional list of reasoning steps to include in PR description
    """
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN not found in environment variables.")

    g = Github(token)
    user = g.get_user()

    parsed = urlparse(repo_url)
    repo_name = parsed.path.strip("/")
    original_repo = g.get_repo(repo_name)

    # Fork repo if not owned
    fork = user.create_fork(original_repo) if original_repo.owner.login != user.login else original_repo

    base_branch = original_repo.default_branch
    new_branch = f"ai-fix-{int(time.time())}"

    # Create new branch from base
    source = fork.get_branch(base_branch)
    fork.create_git_ref(ref=f"refs/heads/{new_branch}", sha=source.commit.sha)

    # Update file in new branch
    contents = fork.get_contents(file_path, ref=new_branch)
    fork.update_file(
        path=file_path,
        message="AI generated bug fix",
        content=fix_code,
        sha=contents.sha,
        branch=new_branch
    )

    # Construct PR description with reasoning
    pr_body = "This pull request was automatically generated by AI.\n\n"
    if reasoning_steps:
        pr_body += "### Step-by-step reasoning:\n"
        for step in reasoning_steps:
            pr_body += f"- **{step['title']}**: {step['description']}\n"

    # Create PR
    pr = original_repo.create_pull(
        title="AI Generated Fix",
        body=pr_body,
        head=f"{user.login}:{new_branch}",
        base=base_branch
    )

    return pr.html_url
