from github import Github
from urllib.parse import urlparse
import os
import time


def create_pull_request(repo_url, fix_code, file_path):

    token = os.getenv("GITHUB_TOKEN")

    g = Github(token)

    user = g.get_user()

    parsed = urlparse(repo_url)
    repo_name = parsed.path.strip("/")

    original_repo = g.get_repo(repo_name)

    # Fork repo
    fork = user.create_fork(original_repo)

    base_branch = original_repo.default_branch

    new_branch = f"ai-fix-{int(time.time())}"

    source = fork.get_branch(base_branch)

    fork.create_git_ref(
        ref=f"refs/heads/{new_branch}",
        sha=source.commit.sha
    )

    contents = fork.get_contents(file_path, ref=new_branch)

    fork.update_file(
        path=file_path,
        message="AI generated bug fix",
        content=fix_code,
        sha=contents.sha,
        branch=new_branch
    )

    pr = original_repo.create_pull(
        title="AI Generated Fix",
        body="This pull request was automatically generated by AI.",
        head=f"{user.login}:{new_branch}",
        base=base_branch
    )

    return pr.html_url
